### PR TITLE
Migrate to app router

### PR DESCRIPTION
**Pull request by tim-phillips**
- **move files to src**
- **move icon and opengraph images to app**
- **move pages to app**
- **dynamically render archive page**

https://nextjs.org/docs/app/building-your-application/routing#the-app-router

### CODE REVIEW

**Review by birthdaycorp — CHANGES_REQUESTED** [review]
The test deployment on vercel appears to be failing due to the use of `useSearchParams` on the archive page. Does this need a suspense boundary?

**Comment by tim-phillips** [comment]
@birthdaycorp it's hard to say without some more context. Could you paste the error message?

**Comment by birthdaycorp** [comment]
@tim-phillips This is what the deployment output looks like:

[08:48:42.157]  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/archive". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
[08:48:42.158]     at a (/vercel/path0/.next/server/chunks/223.js:1:78986)
[08:48:42.161]     at c (/vercel/path0/.next/server/chunks/223.js:1:89983)
[08:48:42.162]     at tt (/vercel/path0/.next/server/app/archive/page.js:1:31030)
[08:48:42.162]     at nj (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
[08:48:42.162]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
[08:48:42.162]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[08:48:42.163]     at nI (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
[08:48:42.163]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
[08:48:42.163]     at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
[08:48:42.163]     at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
[08:48:42.163] 
[08:48:42.164] Error occurred prerendering page "/archive". Read more: https://nextjs.org/docs/messages/prerender-error
[08:48:42.164] 
[08:48:42.339]    Generating static pages (10/14) 
[08:48:42.833]  ✓ Generating static pages (14/14)
[08:48:42.838] 
[08:48:42.839] > Export encountered errors on following paths:
[08:48:42.839] 	/archive/page: /archive
[08:48:42.872] Error: Command "npm run build" exited with 1
[08:48:43.221]

**Comment by tim-phillips** [comment]
@birthdaycorp I made the archive route dynamically rendered so it would behave like the pages router. 

https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional

We can move search into its own component and wrap it in a suspense boundary later.

**Review by birthdaycorp — APPROVED** [review]

**Pull request merged**
