### PR TITLE
Port site to React & Next.js

### LINKED ISSUE #26: Extract nav into reusable component
@tim-phillips is there any reason why we couldn't turn this into a small React component? Or, if that violates the principle of having everything be static HTML, could we define it in one HTML file and add it to individual pages by cloning the element with JS?

### PR DESCRIPTION
**Pull request by tim-phillips**
## Hey!

We're upping our game and porting kchungradio.org over to [React](https://reactjs.org/) and [Next.js](https://nextjs.org/).

### Benefits

This makes it so that changing one link in the nav bar doesn't mean [changing 12 files](https://github.com/kchungradio/kchungradio.org/commit/45253c09cb6a5c19344050cdc381d04705a5c610).

It also enables other amazing things like a unique page for every show.

### Problems

A good number of musicians and artists have some experience poking around some HTML and CSS for their own websites. Moving to the JavaScript world means some increased complexity. Luckily, frameworks like Next.js exist, so you don't have to learn everything about programming, but there is a learning curve.

We don't want our site to stagnate any longer, let's raise all our boats with some modern web skills. 

### Questions

Please ask them! No question will be ignored no matter how unsure of it you are. Your question might prompt more questions, so please try to keep the conversation going. Communication in tech is all about missing a whole bunch of times until it finally connects. 

### Run the website on your computer

Make sure you have these installed:
  - [git](https://git-scm.com/downloads)
  - [node.js](https://nodejs.org)

In your terminal:
  - `git clone https://github.com/kchungradio/kchungradio.org.git`
  - `cd kchungradio.org`
  - `git checkout nextjs`
  - `npm install`
  - `npm run dev`

### Chat

Either post here, or chat in our Slack in #website. 

### Live streams

If there's enough interest, we could do some live streams to get people set up and tour the code, and whatever else we want to talk about.

## To do

- [x] Navbar
- [x] All the pages

Resolves #26

### CODE REVIEW

**Comment by birthdaycorp** [comment]
Hi! I really want to help out with this. Any idea how I can get a copy of the .env file? 

Also....I've spent the last few days turning the existing html into React components, and I can't help but see value in also reorganizing the site. 

- "stream" would be better as its own component (like [this](https://radio.montezpress.com/#/) or [this](https://moonglowradio.net/))
- since the player is the focal point of the site, it might be good to turn the "donate" nav link into a button placed directly below the player
- Since they all direct to an external site, maybe move the wiki, store, and socials links that are currently in the nav to a footer?
- maybe we could add profile pages for the DJs and link to their socials? And an index page that lists them all.

Just some ideas!

**Comment by tim-phillips** [comment]
Awesome! Thanks for the interest in helping out. 

I like these ideas! But let's keep this PR all about a straightforward and simple port, we can put other improvements in separate PRs. I linked some related issues, feel free to comment and create more, not necessary but I find it helpful. 

#12 
#42

**Comment by birthdaycorp** [comment]
I responded to #12  with some questions! 

I got one more though: I'm assuming that you're busy with paid work, right? Currently I'm not. I have free time, and I really want to help out on the redesign of this site so that I can have something to put on my portfolio.

**Comment by tim-phillips** [comment]
Open a PR! You can make a fork off this branch and we can merge your stuff in here.

**Comment by solomon-b** [comment]
I've rebased this PR off the latest `main`, added the missing pages, and added the second stream.

TODO:
- [x] Add the subscription ID to the paypal button on the donate page.
- [x] Fix error handling on media player. For some reason its throwing exceptions when you click pause. I tried a try/catch but it still errored. 
- [x] Fix the vercel deployment.

**Review by solomon-b — APPROVED** [review]
Looks good! I think we are ready to merge.

**Pull request merged**
